"""
Algorithm parameters for gistemp5.
"""

START_YEAR = 1880
END_YEAR = 2026

BASELINE_START_YEAR = 1951
BASELINE_END_YEAR = 1980

EARTH_RADIUS = 6371  # km

NEARBY_STATION_RADIUS = 1200.0  # km

URBAN_ADJUSTMENT_OPTION = False
URBAN_BRIGHTNESS_THRESHOLD = 10
MIN_NEARBY_RURAL_STATIONS = 3
URBAN_NEARBY_RADIUS = 50.0  # km

SST_CUTOFF_TEMP = -1.77  # °C
